version: '3'
services:
  nginx:
    restart: always
    build:
      # dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  backend:
    build:
      # dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - '3001:3001'
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - AWS_RDSDB=${AWS_RDSDB}
  client: 
    build:
      # dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app